---
  name: Check runner versions 
  on:
    workflow_dispatch:
    schedule:
      - cron: '0 0 * * 0'
  
  permissions:
    contents: read
  jobs:
    deploy:
      runs-on: ubuntu-latest
      outputs:
        cache-hit: ${{ steps.cache.outputs.cache-hit }}
        version: ${{ steps.run.outputs.version }}
      steps:
        - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
        - name: Fetch releases
          run: |
            curl -L -H "Accept: application/vnd.github+json" -H "X-GitHub-Api-Version: 2022-11-28" https://api.github.com/repos/actions/runner/releases | grep tag_name > tags.list
          shell: bash
        - uses: actions/cache@v3
          id: cache
          with:
            path: tags.list
            key: ${{ runner.os }}-${{ hashFiles('tags.list') }}
        - name: Get latest version
          id: run
          run: |
            version=`cat tags.list | head -n 1 |  cut -d":" -f 2 | tr -d "\"v, "`
            echo "version=${version}" >> "$GITHUB_OUTPUT"
            echo "version=${version}"
          shell: bash
    build-images:
      permissions:
        contents: read
        packages: write
      needs: deploy
      uses: ./.github/workflows/publish.yaml
      if: needs.deploy.outputs.cache-hit != 'true'
      with:
        runnerVersion: ${{ needs.deploy.outputs.version }}
