---
name: test 
on:
  workflow_dispatch:

permissions:
  contents: write
jobs:
  deploy:
    runs-on: test5
    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
      - name: Run a command
        shell: pwsh
        run: Write-Host "Hello World"
